[package]
name = "my-rs"
version = "0.1.0"
edition = "2021"
# links = "z"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# [[bin]]
# name = "myrs"
# path = "src/main.rs"

[dependencies]
libc = "0.2"

clap = { version = "3.1", features = ["derive"] }
sysinfo = "0.24"
systemstat = "0.1"

raw-cpuid = "10.3.0"

scraper = "0.13.0"

serde = { version = "1.0.137", features = ["derive"] }


log = "0.4.17"
env_logger = "0.9.0"
chrono = "0.4"

reqwest = { version = "0.11", features = ["blocking", "json"] }
tokio = { version = "1", features = ["full"] }

ureq = { version = "2.4", features = ["json"] }

notify-rust = "4"

thiserror = { version = "1.0" }
anyhow = "1.0"

futures = "0.3"


[target.'cfg(unix)'.dependencies]
nix = "0.24.1"
sysctl = "0.4"

[profile.dev]
opt-level = 1

[profile.release]
opt-level = "s"
codegen-units = 1
strip = true
lto = true
incremental = true
