[package]
name = "my-rs"
version = "0.1.0"
edition = "2021"
# links = "z"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# [[bin]]
# name = "myrs"
# path = "src/main.rs"

[dependencies]
clap = { version = "3.1", features = ["derive"]}
bitflags = { version = "1.3" }
local-ip-address = "0.4"
battery = "0.7"
sysinfo = "0.23.5"
raw-cpuid = "10.2.0"

[target.'cfg(unix)'.dependencies]
nix = "0.23.1"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.33.0" }
winapi = { version = "0.3", features = ["winuser"] }

# [build-dependencies]
# cc = "1.0"
# pkg-config = "0.3.24"

[profile.dev]
opt-level = 1
strip = true

[profile.release]
opt-level = "s"
codegen-units = 1
strip = "debuginfo"
lto = "thin"