[package]
name = "my-rs"
version = "0.1.0"
edition = "2021"
# links = "z"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# [[bin]]
# name = "myrs"
# path = "src/main.rs"

[dependencies]
clap = { version = "3.1", features = ["derive"]}
bitflags = { version = "1.3" }
local-ip-address = "0.4"
battery = "0.7"
sysinfo = "0.23.5"
raw-cpuid = "10.3.0"

lru = "0.7.3"
dirs = "4.0"

mp4parse = "0.12.0"
rand = "0.8.5"
socket2 = "0.4.4"

log = "0.4.14"
env_logger = "0.9.0"

reqwest = { version = "0.11", features = ["blocking", "json"] }
tokio = { version = "1", features = ["full"] }

html_parser = "0.6.2"

[target.'cfg(unix)'.dependencies]
nix = "0.23.1"

[target.'cfg(target_os="macos")'.dependencies]
cocoa = "0.24.0"
image-capture-core = { version = "0.1.5" }
# image-capture-core = { git = "https://github.com/brandonhamilton/image-capture-core-rs.git" }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.33.0" }
winapi = { version = "0.3", features = ["winuser"] }

# [build-dependencies]
# cc = "1.0"
# pkg-config = "0.3.24"

[profile.dev]
opt-level = 1

[profile.release]
opt-level = "s"
codegen-units = 1
# strip = "debuginfo"
strip = true
# lto = "thin"
lto = true
incremental = true
