name: Daily Crawl

on:
  schedule:
    - cron: "59 23 * * *"

  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  CARGO_TERM_COLOR: always
  TZ: "Asia/Shanghai"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUST_VERSION: 1.69.0
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Switch Rust version
        run: rustup default ${RUST_VERSION}

      - name: Build
        run: cargo build --verbose

      - name: Run
        run: cargo run -- douban

      - name: Show images
        run: ls ./images

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: images
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: images
          git-config-name: akayj-gh-action
          git-config-email: akayj-gh-action@github.com

      - name: WeChat Work notification by text
        uses: foxundermoon/wechat-work-action@v1
        env:
          WECHAT_WORK_BOT_WEBHOOK: ${{secrets.WECHAT_WORK_BOT_WEBHOOK}}
        with:
          url: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=${{secrets.WECHAT_WORK_BOT_WEBHOOK}}
          type: text
          content: "下载图片成功， 查看 https://github.com/akayj/my-rs/tree/images "
