name: Daily Crawl

on:
  schedule:
    - cron: '59 23 * * *'

  workflow_dispatch:
    

defaults:
  run:
    shell: bash

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUST_VERSION: 1.67.0
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Switch Rust version
        run: rustup default ${RUST_VERSION}

      - name: Build
        run: cargo build --verbose

      - name: Run
        run: cargo run

      - name: Show images
        run: ls ./images

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: images
          git-config-name: akayj-gh-action
          git-config-email: akayj-gh-action@github.com